import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { build } from 'esbuild';

const root = process.cwd();
const webviewDir = path.join(root, 'src', 'webview');

function escapeForInlineScript(source) {
	return source.replace(/<\/script/gi, '<\\/script');
}

const bundleResult = await build({
	entryPoints: [path.join(webviewDir, 'entry.tsx')],
	bundle: true,
	write: false,
	format: 'iife',
	platform: 'browser',
	target: ['es2019'],
	minify: true,
	legalComments: 'none',
	jsx: 'automatic',
	loader: { '.glsl': 'text' },
	define: { 'process.env.NODE_ENV': '"production"' },
	logLevel: 'info',
});

const bundleJs = escapeForInlineScript(bundleResult.outputFiles[0].text);

const [containerJs, buttonJs, glassCss, appCss, template] = await Promise.all([
	readFile(path.join(webviewDir, 'vendor', 'liquid-glass', 'container.js'), 'utf8'),
	readFile(path.join(webviewDir, 'vendor', 'liquid-glass', 'button.js'), 'utf8'),
	readFile(path.join(webviewDir, 'vendor', 'liquid-glass', 'glass.css'), 'utf8'),
	readFile(path.join(webviewDir, 'app.css'), 'utf8'),
	readFile(path.join(webviewDir, 'index.html'), 'utf8'),
]);

const vendorJs = escapeForInlineScript(
	`${containerJs}\n${buttonJs}\nwindow.Container = Container;\nwindow.Button = Button;\n`,
);

function renderHtml(mode) {
	return template
		.replace('__GLASS_CSS__', () => glassCss)
		.replace('__APP_CSS__', () => appCss)
		.replace(/__MODE__/g, () => mode)
		.replace('__VENDOR_SCRIPT__', () => vendorJs)
		.replace('__BUNDLE__', () => bundleJs);
}

const outDir = path.join(root, 'src', 'generated');
await mkdir(outDir, { recursive: true });

const output = `// AUTO-GENERATED by scripts/build-webview.mjs - do not edit by hand.
export const HOME_HTML = ${JSON.stringify(renderHtml('home'))};
export const PICK_HTML = ${JSON.stringify(renderHtml('pick'))};
`;

await writeFile(path.join(outDir, 'effectsHtml.ts'), output, 'utf8');

const sizeKb = Math.round(Buffer.byteLength(output, 'utf8') / 1024);
console.log(`WebView assets generated (${sizeKb} KB) -> src/generated/effectsHtml.ts`);
